Repository Farm-On/BE, pull requests merged in 2025-01, with the labels that each got.

#6 ✨ [Feat] 채팅 관련 API 명세서 작성
  build.gradle
  src/main/java/com/backend/farmon/apiPayload/ApiResponse.java
  src/main/java/com/backend/farmon/apiPayload/code/BaseCode.java
  src/main/java/com/backend/farmon/apiPayload/code/BaseErrorCode.java
  src/main/java/com/backend/farmon/apiPayload/code/ErrorReasonDTO.java
  src/main/java/com/backend/farmon/apiPayload/code/ReasonDTO.java
  src/main/java/com/backend/farmon/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/backend/farmon/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/backend/farmon/apiPayload/exception/ExceptionAdvice.java
  src/main/java/com/backend/farmon/apiPayload/exception/GeneralException.java
  src/main/java/com/backend/farmon/controller/ChatMessageController.java
  src/main/java/com/backend/farmon/controller/ChatRoomController.java
  src/main/java/com/backend/farmon/dto/chat/ChatRequest.java
  src/main/java/com/backend/farmon/dto/chat/ChatResponse.java
Labels: ✨ feature

#9 ✨ [Feat] 농업인/전문가 회원가입/탈퇴 API 명세서 작성
  build.gradle
  src/main/java/com/backend/farmon/apiPayload/ApiResponse.java
  src/main/java/com/backend/farmon/controller/SignupController.java
  src/main/java/com/backend/farmon/dto/user/SignupRequest.java
  src/main/java/com/backend/farmon/dto/user/SignupResponse.java
Labels: ✨ feature

#10 ✨ [Feat] 공동로그인 API 명세서 작성
  src/main/java/com/backend/farmon/controller/LoginController.java
  src/main/java/com/backend/farmon/dto/user/LoginRequestDTO.java
  src/main/java/com/backend/farmon/dto/user/LoginResponseDTO.java
Labels: ✨ feature

#11 ✨ [Feat] 회원정보 수정 페이지 API 명세서 작성
  src/main/java/com/backend/farmon/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/backend/farmon/controller/UserController.java
  src/main/java/com/backend/farmon/dto/user/MypageRequest.java
  src/main/java/com/backend/farmon/dto/user/MypageResponse.java
Labels: ✨ feature

#18 ✨ [Feat] 전문가 프로필 목록/내 프로필 페이지 API 명세서 작성
  src/main/java/com/backend/farmon/controller/ExpertController.java
  src/main/java/com/backend/farmon/dto/expert/ExpertListResponse.java
  src/main/java/com/backend/farmon/dto/expert/ExpertProfileResponse.java
Labels: ✨ feature

#21 ✨ [Feat] 홈 화면 조회, 검색어 삭제 관련 API 명세서 작성
  src/main/java/com/backend/farmon/controller/HomeController.java
  src/main/java/com/backend/farmon/dto/home/HomeResponse.java
Labels: ✨ feature

#23 ✨ [Feat] 농업인 전환, 전문가 전환 API 명세서 작성
  src/main/java/com/backend/farmon/controller/UserController.java
  src/main/java/com/backend/farmon/dto/user/ExchangeResponse.java
Labels: ✨ feature

#25 ♻️ [Refactor] 홈 화면 조회 응답값 수정
  src/main/java/com/backend/farmon/dto/home/HomeResponse.java
Labels: ♻️ refactor

#38 ✨ [Feat] 유저/전문가 관련 엔티티 클래스 추가
  src/main/java/com/backend/farmon/FarmonApplication.java
  src/main/java/com/backend/farmon/domain/Area.java
  src/main/java/com/backend/farmon/domain/Expert.java
  src/main/java/com/backend/farmon/domain/Portfolio.java
  src/main/java/com/backend/farmon/domain/PortfolioImg.java
  src/main/java/com/backend/farmon/domain/User.java
  src/main/java/com/backend/farmon/domain/commons/BaseEntity.java
  src/main/java/com/backend/farmon/domain/enums/Gender.java
  src/main/java/com/backend/farmon/domain/enums/MemberStatus.java
  src/main/java/com/backend/farmon/domain/enums/Role.java
  src/main/java/com/backend/farmon/domain/mapping/ExpertArea.java
  src/main/java/com/backend/farmon/domain/mapping/ExpertCrops.java
Labels: ✨ feature

#39 ✨ [Feat] 채팅 관련 엔티티 클래스 추가
  src/main/java/com/backend/farmon/controller/ChatMessageController.java
  src/main/java/com/backend/farmon/domain/ChatMessage.java
  src/main/java/com/backend/farmon/domain/ChatRoom.java
  src/main/java/com/backend/farmon/domain/commons/BaseEntity.java
  src/main/java/com/backend/farmon/domain/enums/ChatMessageType.java
Labels: ✨ feature

#40 ✨[Feat] Estimate, EstimateImage, Crop, ExpertCrop 도메인 클래스 작성
  src/main/java/com/backend/farmon/controller/EstimateRestController.java
  src/main/java/com/backend/farmon/domain/Crop.java
  src/main/java/com/backend/farmon/domain/Estimate.java
  src/main/java/com/backend/farmon/domain/EstimateImage.java
  src/main/java/com/backend/farmon/domain/Expert.java
  src/main/java/com/backend/farmon/domain/enums/CropCategory.java
  src/main/java/com/backend/farmon/domain/mapping/ExpertCrop.java
  src/main/java/com/backend/farmon/dto/estimate/EstimateResponseDTO.java
Labels: ✨ feature

#30 전체적으로 게시글 API 수정
  src/main/java/com/backend/farmon/controller/PostController.java
  src/main/java/com/backend/farmon/dto/Board/BoardRequestDto.java
  src/main/java/com/backend/farmon/dto/FieldFilterDTO/AllFilterDTO.java
  src/main/java/com/backend/farmon/dto/FieldFilterDTO/FieldCategoryDTO.java
  src/main/java/com/backend/farmon/dto/FieldFilterDTO/KnowHowFilterDTO.java
  src/main/java/com/backend/farmon/dto/FieldFilterDTO/LocationFilterDTO.java
  src/main/java/com/backend/farmon/dto/PostForm/ImgRequestDTO.java
  src/main/java/com/backend/farmon/dto/PostForm/ImgResponseDTO.java
  src/main/java/com/backend/farmon/dto/PostForm/PostRequestDTO.java
  src/main/java/com/backend/farmon/dto/PostForm/PostResponseDTO.java
  src/main/java/com/backend/farmon/dto/PostType.java
Labels: ♻️ refactor

#44 ✨👷[Feat, CI] CI/CD 구축 & API 엔드포인트 통일 & CORS 설정 추가
  .github/workflows/dev-deploy.yml
  Dockerfile
  build.gradle
  docker-compose.yml
  nginx.conf
  src/main/java/com/backend/farmon/config/SwaggerConfig.java
  src/main/java/com/backend/farmon/config/WebConfig.java
  src/main/java/com/backend/farmon/controller/ChatRoomController.java
  src/main/java/com/backend/farmon/controller/CommentController.java
  src/main/java/com/backend/farmon/controller/EstimateRestController.java
  src/main/java/com/backend/farmon/controller/ExpertController.java
  src/main/java/com/backend/farmon/controller/HomeController.java
  src/main/java/com/backend/farmon/controller/LikeController.java
  src/main/java/com/backend/farmon/controller/LoginController.java
  src/main/java/com/backend/farmon/controller/PostController.java
  src/main/java/com/backend/farmon/controller/SignupController.java
  src/main/java/com/backend/farmon/controller/TestController.java
  src/main/java/com/backend/farmon/controller/UserController.java
  src/main/java/com/backend/farmon/domain/Crop.java
  src/main/java/com/backend/farmon/domain/mapping/ExpertArea.java
  src/main/java/com/backend/farmon/domain/mapping/ExpertCrop.java
  src/main/java/com/backend/farmon/dto/Board/BoardRequestDto.java
  src/main/java/com/backend/farmon/dto/PostForm/PostRequestDTO.java
Labels: ✨ feature, 👷 ci

#48 ♻️Feat/post comment controller
  src/main/java/com/backend/farmon/domain/PostImg.java
  src/main/java/com/backend/farmon/dto/Filter/FieldCategory.java
  src/main/java/com/backend/farmon/dto/Filter/FieldCategoryDTO.java
  src/main/java/com/backend/farmon/dto/post/ImgRequestDTO.java
  src/main/java/com/backend/farmon/dto/post/ImgResponseDTO.java
  src/main/java/com/backend/farmon/dto/post/PostRequestDTO.java
  src/main/java/com/backend/farmon/dto/post/PostResponseDTO.java
  src/main/java/com/backend/farmon/dto/post/PostType.java
Labels: ♻️ refactor

#50 ✨[Feat] 채팅방 생성, 입장, 삭제, 조회, 대화 내역 조회, 채팅 견적 상세 보기 로직 구현
  build.gradle
  src/main/java/com/backend/farmon/apiPayload/exception/handler/ChatRoomHandler.java
  src/main/java/com/backend/farmon/apiPayload/exception/handler/EstimateHandler.java
  src/main/java/com/backend/farmon/apiPayload/exception/handler/ExpertHandler.java
  src/main/java/com/backend/farmon/apiPayload/exception/handler/PageHandler.java
  src/main/java/com/backend/farmon/apiPayload/exception/handler/UserHandler.java
  src/main/java/com/backend/farmon/config/QueryDSLConfig.java
  src/main/java/com/backend/farmon/config/WebConfig.java
  src/main/java/com/backend/farmon/controller/ChatRoomController.java
  src/main/java/com/backend/farmon/controller/MessageController.java
  src/main/java/com/backend/farmon/converter/ChatConverter.java
  src/main/java/com/backend/farmon/converter/ConvertTime.java
  src/main/java/com/backend/farmon/domain/ChatMessage.java
  src/main/java/com/backend/farmon/domain/ChatRoom.java
  src/main/java/com/backend/farmon/dto/chat/ChatResponse.java
  src/main/java/com/backend/farmon/repository/ChatMessageRepository/ChatMessageRepository.java
  src/main/java/com/backend/farmon/repository/ChatMessageRepository/ChatMessageRepositoryCustom.java
  src/main/java/com/backend/farmon/repository/ChatMessageRepository/ChatMessageRepositoryImpl.java
  src/main/java/com/backend/farmon/repository/ChatRoomReposiotry/ChatRoomRepository.java
  src/main/java/com/backend/farmon/repository/ChatRoomReposiotry/ChatRoomRepositoryCustom.java
  src/main/java/com/backend/farmon/repository/ChatRoomReposiotry/ChatRoomRepositoryImpl.java
  src/main/java/com/backend/farmon/repository/EstimateRepository/EstimateRepository.java
  src/main/java/com/backend/farmon/repository/EstimateRepository/EstimateRepositoryCustom.java
  src/main/java/com/backend/farmon/repository/EstimateRepository/EstimateRepositoryImpl.java
  src/main/java/com/backend/farmon/repository/ExpertReposiotry/ExpertRepository.java
  src/main/java/com/backend/farmon/repository/ExpertReposiotry/ExpertRepositoryCustom.java
  src/main/java/com/backend/farmon/repository/ExpertReposiotry/ExpertRepositoryImpl.java
  src/main/java/com/backend/farmon/repository/UserRepository/UserRepository.java
  src/main/java/com/backend/farmon/repository/UserRepository/UserRepositoryCustom.java
  src/main/java/com/backend/farmon/repository/UserRepository/UserRepositoryImpl.java
  src/main/java/com/backend/farmon/service/ChatMessageService/ChatMessageQueryService.java
  src/main/java/com/backend/farmon/service/ChatMessageService/ChatMessageQueryServiceImpl.java
  src/main/java/com/backend/farmon/service/ChatRoomService/ChatRoomCommandService.java
  src/main/java/com/backend/farmon/service/ChatRoomService/ChatRoomCommandServiceImpl.java
  src/main/java/com/backend/farmon/service/ChatRoomService/ChatRoomQueryService.java
  src/main/java/com/backend/farmon/service/ChatRoomService/ChatRoomQueryServiceImpl.java
  src/main/java/com/backend/farmon/validaton/annotation/CheckPage.java
  src/main/java/com/backend/farmon/validaton/validator/PageCheckValidator.java
Labels: ✨ feature

#56 ✨Feat: 견적서 API 수정과 기본 CRUD 구현 PR
  src/main/java/com/backend/farmon/controller/EstimateRestController.java
  src/main/java/com/backend/farmon/converter/EstimateConverter.java
  src/main/java/com/backend/farmon/domain/Area.java
  src/main/java/com/backend/farmon/domain/Crop.java
  src/main/java/com/backend/farmon/domain/Estimate.java
  src/main/java/com/backend/farmon/domain/EstimateImage.java
  src/main/java/com/backend/farmon/domain/Expert.java
  src/main/java/com/backend/farmon/domain/ExpertCareer.java
  src/main/java/com/backend/farmon/domain/mapping/ExpertCrop.java
  src/main/java/com/backend/farmon/domain/mapping/ExpertCrops.java
  src/main/java/com/backend/farmon/dto/estimate/EstimateRequestDTO.java
  src/main/java/com/backend/farmon/dto/estimate/EstimateResponseDTO.java
  src/main/java/com/backend/farmon/repository/CropRepository/CropRepository.java
  src/main/java/com/backend/farmon/repository/CropRepository/CropRepositoryCustom.java
  src/main/java/com/backend/farmon/repository/CropRepository/CropRepositoryImpl.java
  src/main/java/com/backend/farmon/repository/EstimateRepository/EstimateRepository.java
  src/main/java/com/backend/farmon/service/EstimateRepository/EstimateCommandService.java
  src/main/java/com/backend/farmon/service/EstimateRepository/EstimateCommandServiceImpl.java
  src/main/java/com/backend/farmon/service/EstimateRepository/EstimateQueryService.java
  src/main/java/com/backend/farmon/service/EstimateRepository/EstimateQueryServiceImpl.java
Labels: ✨ feature

#59 ✨[Feat] 농업인-전문가 전환, 홈 화면 커뮤니티 게시글(Q&A, 전문가 칼럼 제외) 조회 구현
  src/main/java/com/backend/farmon/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/backend/farmon/controller/HomeController.java
  src/main/java/com/backend/farmon/controller/UserController.java
  src/main/java/com/backend/farmon/converter/HomeConverter.java
  src/main/java/com/backend/farmon/converter/UserConverter.java
  src/main/java/com/backend/farmon/domain/Board.java
  src/main/java/com/backend/farmon/domain/Img.java
  src/main/java/com/backend/farmon/domain/LikeCount.java
  src/main/java/com/backend/farmon/domain/Post.java
  src/main/java/com/backend/farmon/domain/PostImg.java
  src/main/java/com/backend/farmon/dto/user/ExchangeResponse.java
  src/main/java/com/backend/farmon/repository/CommendRepository/CommentRepository.java
  src/main/java/com/backend/farmon/repository/CommendRepository/CommentRepositoryCustom.java
  src/main/java/com/backend/farmon/repository/CommendRepository/CommentRepositoryImpl.java
  src/main/java/com/backend/farmon/repository/ExpertReposiotry/ExpertRepository.java
  src/main/java/com/backend/farmon/repository/LikeCountRepository/LikeCountRepository.java
  src/main/java/com/backend/farmon/repository/LikeCountRepository/LikeCountRepositoryCustom.java
  src/main/java/com/backend/farmon/repository/LikeCountRepository/LikeCountRepositoryImpl.java
  src/main/java/com/backend/farmon/repository/PostRepository/PostRepository.java
  src/main/java/com/backend/farmon/repository/PostRepository/PostRepositoryCustom.java
  src/main/java/com/backend/farmon/repository/PostRepository/PostRepositoryImpl.java
  src/main/java/com/backend/farmon/service/PostService/PostQueryService.java
  src/main/java/com/backend/farmon/service/PostService/PostQueryServiceImpl.java
  src/main/java/com/backend/farmon/service/UserService/UserQueryService.java
  src/main/java/com/backend/farmon/service/UserService/UserQueryServiceImpl.java
  src/main/java/com/backend/farmon/strategy/postType/AllPostFetchStrategy.java
  src/main/java/com/backend/farmon/strategy/postType/PopularPostFetchStrategy.java
  src/main/java/com/backend/farmon/strategy/postType/PostFetchStrategy.java
  src/main/java/com/backend/farmon/strategy/postType/PostFetchStrategyFactory.java
Labels: ✨ feature

#65 ✨[Feat] JWT 토큰 이용한 로그인/농업인 회원가입 api 구현
  build.gradle
  src/main/java/com/backend/farmon/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/backend/farmon/config/security/CustomUserDetailsService.java
  src/main/java/com/backend/farmon/config/security/JWTAuthenticationFilter.java
  src/main/java/com/backend/farmon/config/security/JWTUtil.java
  src/main/java/com/backend/farmon/config/security/SecurityConfig.java
  src/main/java/com/backend/farmon/config/security/UserAuthorizationUtil.java
  src/main/java/com/backend/farmon/controller/LoginController.java
  src/main/java/com/backend/farmon/controller/SignupController.java
  src/main/java/com/backend/farmon/converter/SignupConverter.java
  src/main/java/com/backend/farmon/domain/User.java
  src/main/java/com/backend/farmon/dto/user/CustomUserDetails.java
  src/main/java/com/backend/farmon/dto/user/LoginResponseDTO.java
  src/main/java/com/backend/farmon/dto/user/SignupRequest.java
  src/main/java/com/backend/farmon/repository/UserRepository/UserRepository.java
  src/main/java/com/backend/farmon/service/UserService/LoginService.java
  src/main/java/com/backend/farmon/service/UserService/UserCommandService.java
  src/main/java/com/backend/farmon/service/UserService/UserCommandServiceImpl.java
Labels: ✨ feature

#68 ✨ [Feat] PostController (피그마에 있는 이름으로 통일 ) + S3 설정
  build.gradle
  src/main/java/com/backend/farmon/aws/s3/AmazonS3Manager.java
  src/main/java/com/backend/farmon/aws/s3/UuidRepository.java
  src/main/java/com/backend/farmon/config/AmazonConfig.java
  src/main/java/com/backend/farmon/controller/PostController.java
  src/main/java/com/backend/farmon/domain/Board.java
  src/main/java/com/backend/farmon/domain/Post.java
  src/main/java/com/backend/farmon/dto/Board/BoardRequestDto.java
  src/main/java/com/backend/farmon/dto/FieldFilterDTO/AllFilterDTO.java
  src/main/java/com/backend/farmon/dto/FieldFilterDTO/FieldCategoryDTO.java
  src/main/java/com/backend/farmon/dto/FieldFilterDTO/KnowHowFilterDTO.java
  src/main/java/com/backend/farmon/dto/FieldFilterDTO/LocationFilterDTO.java
  src/main/java/com/backend/farmon/dto/PostForm/PostRequestDTO.java
  src/main/java/com/backend/farmon/dto/PostForm/PostResponseDTO.java
  src/main/java/com/backend/farmon/dto/PostType.java
  src/main/java/com/backend/farmon/repository/LikeCountRepository/LikeCountRepositoryCustom.java
  src/main/java/com/backend/farmon/repository/LikeCountRepository/LikeCountRepositoryImpl.java
  src/main/java/com/backend/farmon/service/CommentService/CommentService.java
  src/main/java/com/backend/farmon/service/CommentService/CommentServiceImpl.java
  src/main/java/com/backend/farmon/service/LikeService/LikeService.java
Labels: ✨ feature

#70 [Fix] build, 브랜치 충돌 오류 수정
  build.gradle
  src/main/java/com/backend/farmon/config/security/JWTAuthenticationFilter.java
  src/main/java/com/backend/farmon/dto/Board/BoardRequestDto.java
  src/main/java/com/backend/farmon/repository/CommendRepository/CommentRepositoryCustom.java
  src/main/java/com/backend/farmon/repository/CommentRepository/CommentRepository.java
  src/main/java/com/backend/farmon/repository/CommentRepository/CommentRepositoryCustom.java
  src/main/java/com/backend/farmon/repository/CommentRepository/CommentRepositoryImpl.java
  src/main/java/com/backend/farmon/service/PostService/PostQueryServiceImpl.java
Labels: 🐛 fix

#74 PostController(PostForm 삭제 및 S3 및 나머지 api 전체 수정)
  src/main/java/com/backend/farmon/aws/s3/AmazonS3Manager.java
  src/main/java/com/backend/farmon/controller/PostController.java
  src/main/java/com/backend/farmon/domain/Answer.java
  src/main/java/com/backend/farmon/domain/Post.java
  src/main/java/com/backend/farmon/domain/User.java
  src/main/java/com/backend/farmon/dto/Answer/AnswerRequestDTO.java
  src/main/java/com/backend/farmon/dto/Board/BoardRequestDto.java
  src/main/java/com/backend/farmon/dto/Filter/FieldCategory.java
  src/main/java/com/backend/farmon/dto/PostForm/ImgRequestDTO.java
  src/main/java/com/backend/farmon/dto/PostForm/ImgResponseDTO.java
  src/main/java/com/backend/farmon/dto/PostForm/PostRequestDTO.java
  src/main/java/com/backend/farmon/dto/PostForm/PostResponseDTO.java
Labels: ♻️ refactor

#80 ♻️[Refactor] UserAuthorizationUtil함수 추가 및 로그인 응답 DTO 수정
  src/main/java/com/backend/farmon/config/security/UserAuthorizationUtil.java
  src/main/java/com/backend/farmon/controller/LoginController.java
  src/main/java/com/backend/farmon/dto/user/LoginResponseDTO.java
  src/main/java/com/backend/farmon/service/UserService/LoginService.java
Labels: ♻️ refactor

#82 ✨[Feat] 견적서 목록 가져오기 Paging 관련 API 구현 & Estimate Entity 수정 PR
  src/main/java/com/backend/farmon/controller/EstimateRestController.java
  src/main/java/com/backend/farmon/converter/ChatConverter.java
  src/main/java/com/backend/farmon/converter/EstimateConverter.java
  src/main/java/com/backend/farmon/domain/Crop.java
  src/main/java/com/backend/farmon/domain/Estimate.java
  src/main/java/com/backend/farmon/dto/estimate/EstimateResponseDTO.java
  src/main/java/com/backend/farmon/repository/AreaRepository/AreaRepository.java
  src/main/java/com/backend/farmon/repository/AreaRepository/AreaRepositoryCustom.java
  src/main/java/com/backend/farmon/repository/AreaRepository/AreaRepositoryImpl.java
  src/main/java/com/backend/farmon/repository/EstimateRepository/EstimateRepository.java
  src/main/java/com/backend/farmon/service/EstimateRepository/EstimateCommandService.java
  src/main/java/com/backend/farmon/service/EstimateRepository/EstimateQueryService.java
  src/main/java/com/backend/farmon/service/EstimateRepository/EstimateQueryServiceImpl.java
  src/main/java/com/backend/farmon/service/EstimateService/EstimateCommandService.java
  src/main/java/com/backend/farmon/service/EstimateService/EstimateCommandServiceImpl.java
  src/main/java/com/backend/farmon/service/EstimateService/EstimateQueryService.java
  src/main/java/com/backend/farmon/service/EstimateService/EstimateQueryServiceImpl.java
Labels: ✨ feature, ♻️ refactor

#88 ♻️✨[Refactor, Feat] 채팅방 견적 주소 수정, 토큰과 파라미터의 userId 일치 검증 추가
  .github/workflows/dev-deploy.yml
  build.gradle
  docker-compose.yml
  src/main/java/com/backend/farmon/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/backend/farmon/apiPayload/exception/handler/AuthorizationHandler.java
  src/main/java/com/backend/farmon/config/RedisConfig.java
  src/main/java/com/backend/farmon/controller/ChatRoomController.java
  src/main/java/com/backend/farmon/controller/TestController.java
  src/main/java/com/backend/farmon/converter/ChatConverter.java
  src/main/java/com/backend/farmon/dto/chat/ChatResponse.java
  src/main/java/com/backend/farmon/service/ChatRoomService/ChatRoomCommandServiceImpl.java
  src/main/java/com/backend/farmon/service/ChatRoomService/ChatRoomQueryServiceImpl.java
  src/main/java/com/backend/farmon/service/UserService/UserQueryServiceImpl.java
  src/main/java/com/backend/farmon/validaton/annotation/EqualsUserId.java
  src/main/java/com/backend/farmon/validaton/validator/UserIdEqualsValidator.java
Labels: ✨ feature, ♻️ refactor

#92 ✨ Feat S3 서비스 구현 및 좋아요 기능 개발 , BoardService 개발
  src/main/java/com/backend/farmon/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/backend/farmon/controller/CommentController.java
  src/main/java/com/backend/farmon/controller/LikeController.java
  src/main/java/com/backend/farmon/controller/PostController.java
  src/main/java/com/backend/farmon/domain/Answer.java
  src/main/java/com/backend/farmon/domain/Comment.java
  src/main/java/com/backend/farmon/domain/LikeCount.java
  src/main/java/com/backend/farmon/domain/Post.java
  src/main/java/com/backend/farmon/dto/Board/BoardRequestDto.java
  src/main/java/com/backend/farmon/repository/BoardRepository/BoardRepository.java
  src/main/java/com/backend/farmon/repository/LikeCountRepository/LikeCountRepository.java
  src/main/java/com/backend/farmon/repository/PostRepository/PostImgRepository.java
  src/main/java/com/backend/farmon/service/AWS/S3Service.java
  src/main/java/com/backend/farmon/service/BoardService/BoardService.java
  src/main/java/com/backend/farmon/service/BoardService/BoardServiceImpl.java
  src/main/java/com/backend/farmon/service/LikeService/LikeService.java
  src/main/java/com/backend/farmon/service/LikeService/LikeServiceImpl.java
Labels: ✨ feature

#96 ✨[Feat] 전문가 회원가입, 전문가 경력/추가정보 CRUD api 구현
  src/main/java/com/backend/farmon/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/backend/farmon/apiPayload/exception/handler/AreaHandler.java
  src/main/java/com/backend/farmon/apiPayload/exception/handler/CropHandler.java
  src/main/java/com/backend/farmon/apiPayload/exception/handler/ExpertCareerHandler.java
  src/main/java/com/backend/farmon/apiPayload/exception/handler/ExpertDetailHandler.java
  src/main/java/com/backend/farmon/controller/ExpertController.java
  src/main/java/com/backend/farmon/controller/LoginController.java
  src/main/java/com/backend/farmon/controller/SignupController.java
  src/main/java/com/backend/farmon/converter/ExpertConverter.java
  src/main/java/com/backend/farmon/converter/SignupConverter.java
  src/main/java/com/backend/farmon/domain/Area.java
  src/main/java/com/backend/farmon/domain/Crop.java
  src/main/java/com/backend/farmon/domain/Expert.java
  src/main/java/com/backend/farmon/domain/ExpertCareer.java
  src/main/java/com/backend/farmon/domain/ExpertDatail.java
  src/main/java/com/backend/farmon/dto/expert/ExpertCareerRequest.java
  src/main/java/com/backend/farmon/dto/expert/ExpertCareerResponse.java
  src/main/java/com/backend/farmon/dto/expert/ExpertDetailRequest.java
  src/main/java/com/backend/farmon/dto/expert/ExpertDetailResponse.java
  src/main/java/com/backend/farmon/dto/user/SignupRequest.java
  src/main/java/com/backend/farmon/dto/user/SignupResponse.java
  src/main/java/com/backend/farmon/repository/AreaRepository/AreaRepository.java
  src/main/java/com/backend/farmon/repository/AreaRepository/AreaRepositoryCustom.java
  src/main/java/com/backend/farmon/repository/AreaRepository/AreaRepositoryImpl.java
  src/main/java/com/backend/farmon/repository/CropRepository/CropRepository.java
  src/main/java/com/backend/farmon/repository/ExpertCareerRepository/ExpertCareerRepository.java
  src/main/java/com/backend/farmon/repository/ExpertDetailRepository/ExpertDetailRepository.java
  src/main/java/com/backend/farmon/service/ExpertService/ExpertCommandService.java
  src/main/java/com/backend/farmon/service/ExpertService/ExpertCommandServiceImpl.java
  src/main/java/com/backend/farmon/service/ExpertService/ExpertQueryService.java
  src/main/java/com/backend/farmon/service/ExpertService/ExpertQueryServiceImpl.java
Labels: ✨ feature

#99 ✨[Feat] 채팅 메시지(입장, 퇴장, 텍스트, 컨설팅 완료) 보내기&받기 구현
  build.gradle
  src/main/java/com/backend/farmon/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/backend/farmon/apiPayload/exception/handler/ChatMessageHandler.java
  src/main/java/com/backend/farmon/config/chat/FilterChannelInterceptor.java
  src/main/java/com/backend/farmon/config/chat/SessionInfo.java
  src/main/java/com/backend/farmon/config/chat/StompHandshakeInterceptor.java
  src/main/java/com/backend/farmon/config/chat/WebSocketSessionManager.java
  src/main/java/com/backend/farmon/config/chat/WebSocketStompConfig.java
  src/main/java/com/backend/farmon/controller/ChatRoomController.java
  src/main/java/com/backend/farmon/controller/MessageController.java
  src/main/java/com/backend/farmon/converter/ChatConverter.java
  src/main/java/com/backend/farmon/domain/ChatMessage.java
  src/main/java/com/backend/farmon/domain/enums/ChatMessageType.java
  src/main/java/com/backend/farmon/dto/chat/ChatRequest.java
  src/main/java/com/backend/farmon/dto/chat/ChatResponse.java
  src/main/java/com/backend/farmon/repository/ChatMessageRepository/ChatMessageRepository.java
  src/main/java/com/backend/farmon/repository/ChatMessageRepository/ChatMessageRepositoryImpl.java
  src/main/java/com/backend/farmon/repository/ChatRoomReposiotry/ChatRoomRepositoryCustom.java
  src/main/java/com/backend/farmon/repository/ChatRoomReposiotry/ChatRoomRepositoryImpl.java
  src/main/java/com/backend/farmon/service/ChatMessageService/ChatMessageCommandService.java
  src/main/java/com/backend/farmon/service/ChatMessageService/ChatMessageCommandServiceImpl.java
  src/main/java/com/backend/farmon/service/ChatMessageService/ChatMessageQueryServiceImpl.java
  src/main/java/com/backend/farmon/service/ChatRoomService/ChatRoomCommandService.java
  src/main/java/com/backend/farmon/service/ChatRoomService/ChatRoomCommandServiceImpl.java
  src/main/java/com/backend/farmon/service/ChatRoomService/ChatRoomQueryService.java
  src/main/java/com/backend/farmon/service/ChatRoomService/ChatRoomQueryServiceImpl.java
Labels: ✨ feature

#100 ✨[Feat] 전문가 프로필 이미지, 대표서비스, 활동지역 편집 api구현
  src/main/java/com/backend/farmon/controller/ExpertController.java
  src/main/java/com/backend/farmon/converter/ExpertConverter.java
  src/main/java/com/backend/farmon/domain/Expert.java
  src/main/java/com/backend/farmon/dto/expert/ExpertProfileRequest.java
  src/main/java/com/backend/farmon/dto/expert/ExpertProfileResponse.java
  src/main/java/com/backend/farmon/service/AWS/S3Service.java
  src/main/java/com/backend/farmon/service/ExpertService/ExpertCommandService.java
  src/main/java/com/backend/farmon/service/ExpertService/ExpertCommandServiceImpl.java
Labels: ✨ feature

#102 ♻️[Refactor] 로그인 토큰, 전문가 회원가입 api 수정
  src/main/java/com/backend/farmon/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/backend/farmon/controller/SignupController.java
  src/main/java/com/backend/farmon/converter/SignupConverter.java
  src/main/java/com/backend/farmon/dto/user/SignupRequest.java
  src/main/java/com/backend/farmon/dto/user/SignupResponse.java
  src/main/java/com/backend/farmon/repository/ExpertReposiotry/ExpertRepository.java
  src/main/java/com/backend/farmon/service/ExpertService/ExpertCommandService.java
  src/main/java/com/backend/farmon/service/ExpertService/ExpertCommandServiceImpl.java
  src/main/java/com/backend/farmon/service/UserService/LoginService.java
Labels: ♻️ refactor

#103 ✨[Feat] 견적서 찾기 필터링, 이미지 저장, 작물 및 지역 id 가져오기 수정 PR
  src/main/java/com/backend/farmon/config/AmazonConfig.java
  src/main/java/com/backend/farmon/controller/EstimateRestController.java
  src/main/java/com/backend/farmon/converter/EstimateConverter.java
  src/main/java/com/backend/farmon/converter/MultipartJackson2HttpMessageConverter.java
  src/main/java/com/backend/farmon/domain/Estimate.java
  src/main/java/com/backend/farmon/domain/EstimateImage.java
  src/main/java/com/backend/farmon/dto/estimate/EstimateRequestDTO.java
  src/main/java/com/backend/farmon/dto/estimate/EstimateResponseDTO.java
  src/main/java/com/backend/farmon/repository/AreaRepository/AreaRepository.java
  src/main/java/com/backend/farmon/repository/EstimateImageRepository/EstimateImageRepository.java
  src/main/java/com/backend/farmon/repository/EstimateImageRepository/EstimateImageRepositoryCustom.java
  src/main/java/com/backend/farmon/repository/EstimateImageRepository/EstimateImageRepositoryImpl.java
  src/main/java/com/backend/farmon/repository/EstimateRepository/EstimateRepository.java
  src/main/java/com/backend/farmon/repository/EstimateRepository/EstimateRepositoryCustom.java
  src/main/java/com/backend/farmon/repository/EstimateRepository/EstimateRepositoryImpl.java
  src/main/java/com/backend/farmon/service/EstimateService/EstimateCommandService.java
  src/main/java/com/backend/farmon/service/EstimateService/EstimateCommandServiceImpl.java
  src/main/java/com/backend/farmon/service/EstimateService/EstimateQueryService.java
  src/main/java/com/backend/farmon/service/EstimateService/EstimateQueryServiceImpl.java
Labels: ✨ feature, ♻️ refactor

#104 ♻️ refactoring /comment 댓글 api 전체 수정 및 컨버터 제작 ,dto 수정
  src/main/java/com/backend/farmon/config/AmazonConfig.java
  src/main/java/com/backend/farmon/controller/CommentController.java
  src/main/java/com/backend/farmon/converter/CommentConverter.java
  src/main/java/com/backend/farmon/domain/Comment.java
  src/main/java/com/backend/farmon/dto/Comment/CommenResponseDTO.java
  src/main/java/com/backend/farmon/dto/Comment/CommentRequestDTO.java
  src/main/java/com/backend/farmon/dto/Comment/CommentResponseDTO.java
Labels: ♻️ refactor

#108 ✨[Feat] 채팅방 목록 조회 검색어 필터링 추가, 홈 화면 API 명세서 수정
  src/main/java/com/backend/farmon/controller/ChatRoomController.java
  src/main/java/com/backend/farmon/controller/HomeController.java
  src/main/java/com/backend/farmon/converter/ChatConverter.java
  src/main/java/com/backend/farmon/dto/chat/ChatRequest.java
  src/main/java/com/backend/farmon/dto/chat/ChatResponse.java
  src/main/java/com/backend/farmon/dto/home/HomeResponse.java
  src/main/java/com/backend/farmon/repository/ChatMessageRepository/ChatMessageRepository.java
  src/main/java/com/backend/farmon/repository/ChatRoomReposiotry/ChatRoomRepositoryCustom.java
  src/main/java/com/backend/farmon/repository/ChatRoomReposiotry/ChatRoomRepositoryImpl.java
  src/main/java/com/backend/farmon/service/ChatRoomService/ChatRoomQueryService.java
  src/main/java/com/backend/farmon/service/ChatRoomService/ChatRoomQueryServiceImpl.java
Labels: ✨ feature
