Repository Farm-On/BE, pull requests merged in 2025-02, with the labels that each got.

#111 ♻️[Refactor] 채팅 메시지 전송 시간 포맷 변경, Post 엔티티 좋아요 횟수 컬럼 오타 수정
  src/main/java/com/backend/farmon/converter/ConvertTime.java
  src/main/java/com/backend/farmon/domain/Post.java
  src/main/java/com/backend/farmon/repository/ChatMessageRepository/ChatMessageRepository.java
  src/main/java/com/backend/farmon/service/ChatRoomService/ChatRoomQueryServiceImpl.java
Labels: 🐛 fix, ♻️ refactor

#113 ✨Feat: deleteEstimate 서비스에 aws S3 File원격삭제 구현
  src/main/java/com/backend/farmon/aws/s3/AmazonS3Manager.java
  src/main/java/com/backend/farmon/controller/EstimateRestController.java
  src/main/java/com/backend/farmon/repository/EstimateRepository/EstimateRepositoryCustom.java
  src/main/java/com/backend/farmon/repository/EstimateRepository/EstimateRepositoryImpl.java
  src/main/java/com/backend/farmon/service/EstimateService/EstimateCommandServiceImpl.java
  src/main/java/com/backend/farmon/service/EstimateService/EstimateQueryService.java
  src/main/java/com/backend/farmon/service/EstimateService/EstimateQueryServiceImpl.java
Labels: ✨ feature

#115 🐛[Fix] 채팅 메시지 시간 포맷 오류 수정
  nginx.conf
  src/main/java/com/backend/farmon/converter/ConvertTime.java
Labels: 🐛 fix

#114 ✨Feat: 회원탈퇴 api, 전문가 추가정보 api 수정
  src/main/java/com/backend/farmon/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/backend/farmon/apiPayload/exception/handler/ExpertDetailHandler.java
  src/main/java/com/backend/farmon/config/security/CustomUserDetailsService.java
  src/main/java/com/backend/farmon/controller/ExpertController.java
  src/main/java/com/backend/farmon/controller/SignupController.java
  src/main/java/com/backend/farmon/converter/ExpertConverter.java
  src/main/java/com/backend/farmon/domain/Expert.java
  src/main/java/com/backend/farmon/domain/ExpertDatail.java
  src/main/java/com/backend/farmon/dto/expert/ExpertDetailRequest.java
  src/main/java/com/backend/farmon/dto/expert/ExpertDetailResponse.java
  src/main/java/com/backend/farmon/dto/expert/ExpertProfileResponse.java
  src/main/java/com/backend/farmon/repository/ExpertDetailRepository/ExpertDetailRepository.java
  src/main/java/com/backend/farmon/service/AWS/S3Service.java
  src/main/java/com/backend/farmon/service/ExpertService/ExpertCommandService.java
  src/main/java/com/backend/farmon/service/ExpertService/ExpertCommandServiceImpl.java
Labels: ✨ feature, ♻️ refactor

#116 🐛[Fix] Dockerfile timezone 변경
  Dockerfile
Labels: 🐛 fix, 👷 ci

#118 🐛[Fix] cors 허용 origin, method 변경
  src/main/java/com/backend/farmon/config/WebConfig.java
Labels: 🐛 fix

#119 ✨Feat: 필터링시 완료된 견적 제외해서 보여주도록 수정 PR
  src/main/java/com/backend/farmon/repository/EstimateRepository/EstimateRepositoryImpl.java
Labels: ✨ feature

#120 ✨Feat: image 업로드 5개 제한, 날짜 정보 반환 형식 수정
  src/main/java/com/backend/farmon/converter/EstimateConverter.java
  src/main/java/com/backend/farmon/dto/estimate/EstimateResponseDTO.java
  src/main/java/com/backend/farmon/service/EstimateService/EstimateCommandServiceImpl.java
Labels: ✨ feature

#123 ✨[Feat] 로그인 여부에 따른 인증 권한 설정 추가
  docker-compose.yml
  src/main/java/com/backend/farmon/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/backend/farmon/apiPayload/exception/ExceptionAdvice.java
  src/main/java/com/backend/farmon/config/WebConfig.java
  src/main/java/com/backend/farmon/config/security/CustomAccessDeniedHandler.java
  src/main/java/com/backend/farmon/config/security/CustomAuthenticationEntryPoint.java
  src/main/java/com/backend/farmon/config/security/SecurityConfig.java
  src/main/java/com/backend/farmon/controller/HomeController.java
Labels: ✨ feature

#126 ✨[Feat] 홈 화면 추천 검색어 리스트 조회 구현
  src/main/java/com/backend/farmon/FarmonApplication.java
  src/main/java/com/backend/farmon/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/backend/farmon/apiPayload/exception/ExceptionAdvice.java
  src/main/java/com/backend/farmon/config/AsyncConfig.java
  src/main/java/com/backend/farmon/config/RedisConfig.java
  src/main/java/com/backend/farmon/config/security/SecurityConfig.java
  src/main/java/com/backend/farmon/controller/ChatRoomController.java
  src/main/java/com/backend/farmon/controller/HomeController.java
  src/main/java/com/backend/farmon/controller/TestController.java
  src/main/java/com/backend/farmon/dto/post/PostType.java
  src/main/java/com/backend/farmon/service/ChatRoomService/ChatRoomCommandService.java
  src/main/java/com/backend/farmon/service/ChatRoomService/ChatRoomCommandServiceImpl.java
  src/main/java/com/backend/farmon/service/EstimateService/EstimateCommandServiceImpl.java
  src/main/java/com/backend/farmon/service/SearchService/SearchCommandService.java
  src/main/java/com/backend/farmon/service/SearchService/SearchCommandServiceImpl.java
  src/main/java/com/backend/farmon/service/SearchService/SearchQueryService.java
  src/main/java/com/backend/farmon/service/SearchService/SearchQueryServiceImpl.java
Labels: ✨ feature

#130 ✨Feat: 제안받은 견적 리스트 API, 농업인/내견적 전문가 직접찾기 API 추가구현 PR
  src/main/java/com/backend/farmon/controller/EstimateRestController.java
  src/main/java/com/backend/farmon/converter/EstimateConverter.java
  src/main/java/com/backend/farmon/dto/estimate/EstimateResponseDTO.java
  src/main/java/com/backend/farmon/repository/ChatRoomReposiotry/ChatRoomRepository.java
  src/main/java/com/backend/farmon/repository/ExpertReposiotry/ExpertRepository.java
  src/main/java/com/backend/farmon/service/EstimateService/EstimateQueryService.java
  src/main/java/com/backend/farmon/service/EstimateService/EstimateQueryServiceImpl.java
Labels: ✨ feature

#131 ✨[Feat] 홈 화면 자동 완성 검색어 목록 조회 구현
  .github/workflows/dev-deploy.yml
  redis.conf
  src/main/java/com/backend/farmon/config/RedisConfig.java
  src/main/java/com/backend/farmon/config/security/SecurityConfig.java
  src/main/java/com/backend/farmon/controller/HomeController.java
  src/main/java/com/backend/farmon/controller/TestController.java
  src/main/java/com/backend/farmon/controller/UserController.java
  src/main/java/com/backend/farmon/converter/HomeConverter.java
  src/main/java/com/backend/farmon/repository/CropRepository/CropRepository.java
  src/main/java/com/backend/farmon/service/ChatRoomService/ChatRoomQueryServiceImpl.java
  src/main/java/com/backend/farmon/service/SearchService/SearchCommandServiceImpl.java
  src/main/java/com/backend/farmon/service/SearchService/SearchQueryService.java
  src/main/java/com/backend/farmon/service/SearchService/SearchQueryServiceImpl.java
Labels: ✨ feature

#133 ✨ [Feat]/post comment controller
  src/main/java/com/backend/farmon/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/backend/farmon/controller/CommentController.java
  src/main/java/com/backend/farmon/controller/LikeController.java
  src/main/java/com/backend/farmon/controller/PostController.java
  src/main/java/com/backend/farmon/converter/CommentConverter.java
  src/main/java/com/backend/farmon/converter/FieldCategoryConverter.java
  src/main/java/com/backend/farmon/domain/Answer.java
  src/main/java/com/backend/farmon/domain/AnswerImg.java
  src/main/java/com/backend/farmon/domain/Board.java
  src/main/java/com/backend/farmon/domain/Comment.java
  src/main/java/com/backend/farmon/domain/FieldCategoryEntity.java
  src/main/java/com/backend/farmon/domain/LikeCount.java
  src/main/java/com/backend/farmon/domain/Post.java
  src/main/java/com/backend/farmon/domain/SubCategory.java
  src/main/java/com/backend/farmon/dto/Board/BoardRequestDto.java
  src/main/java/com/backend/farmon/dto/Comment/CommentRequestDTO.java
  src/main/java/com/backend/farmon/dto/Comment/CommentResponseDTO.java
  src/main/java/com/backend/farmon/dto/Filter/FieldCategoryDTO.java
  src/main/java/com/backend/farmon/dto/Filter/SubCategoryDTO.java
  src/main/java/com/backend/farmon/dto/like/LikeRequestDTO.java
  src/main/java/com/backend/farmon/dto/like/LikeResponseDTO.java
  src/main/java/com/backend/farmon/dto/post/PostPagingResponseDTO.java
  src/main/java/com/backend/farmon/dto/post/PostRequestDTO.java
  src/main/java/com/backend/farmon/dto/post/PostResponseDTO.java
  src/main/java/com/backend/farmon/dto/post/PostType.java
  src/main/java/com/backend/farmon/repository/BoardRepository/BoardRepository.java
  src/main/java/com/backend/farmon/repository/CommentRepository/CommentRepository.java
  src/main/java/com/backend/farmon/repository/CommentRepository/CommentRepositoryCustom.java
  src/main/java/com/backend/farmon/repository/FilterRepository/FieldCategoryRepository.java
  src/main/java/com/backend/farmon/repository/FilterRepository/SubCategoryRepository.java
  src/main/java/com/backend/farmon/repository/PostRepository/PostRepository.java
  src/main/java/com/backend/farmon/repository/PostRepository/PostRepositoryCustom.java
  src/main/java/com/backend/farmon/repository/PostRepository/PostRepositoryImpl.java
  src/main/java/com/backend/farmon/repository/UserRepository/UserRepository.java
  src/main/java/com/backend/farmon/service/BoardService/BoardService.java
  src/main/java/com/backend/farmon/service/BoardService/BoardServiceImpl.java
  src/main/java/com/backend/farmon/service/ChatRoomService/ChatRoomQueryServiceImpl.java
  src/main/java/com/backend/farmon/service/CommentService/CommentService.java
  src/main/java/com/backend/farmon/service/CommentService/CommentServiceImpl.java
  src/main/java/com/backend/farmon/service/LikeService/LikeServiceImpl.java
  src/main/java/com/backend/farmon/service/PostService/PostQueryService.java
  src/main/java/com/backend/farmon/service/PostService/PostQueryServiceImpl.java
  src/main/java/com/backend/farmon/strategy/postType/PostFetchStrategyFactory.java
Labels: ✨ feature

#135 ♻️[Refactor] 채팅 평균 응답 시간 정보 삭제
  src/main/java/com/backend/farmon/controller/ChatRoomController.java
  src/main/java/com/backend/farmon/converter/ChatConverter.java
  src/main/java/com/backend/farmon/domain/User.java
  src/main/java/com/backend/farmon/dto/chat/ChatResponse.java
Labels: ♻️ refactor

#140 ✨[Feat] 채팅 시 전송할 이미지 업로드 API 구현
  src/main/java/com/backend/farmon/FarmonApplication.java
  src/main/java/com/backend/farmon/controller/ChatRoomController.java
  src/main/java/com/backend/farmon/converter/ChatConverter.java
  src/main/java/com/backend/farmon/dto/chat/ChatResponse.java
  src/main/java/com/backend/farmon/service/AWS/S3Service.java
  src/main/java/com/backend/farmon/service/ChatMessageService/ChatMessageCommandServiceImpl.java
  src/main/java/com/backend/farmon/service/ChatRoomService/ChatRoomCommandServiceImpl.java
  src/main/java/com/backend/farmon/service/ChatRoomService/ChatRoomQueryService.java
  src/main/java/com/backend/farmon/service/ChatRoomService/ChatRoomQueryServiceImpl.java
  src/main/java/com/backend/farmon/service/SearchService/SearchQueryServiceImpl.java
Labels: ✨ feature

#142 ♻️Refactor: 견적 코드 Refactoring & recent5 API 리포지토리 수정
  src/main/java/com/backend/farmon/controller/EstimateRestController.java
  src/main/java/com/backend/farmon/dto/estimate/EstimateRequestDTO.java
  src/main/java/com/backend/farmon/repository/EstimateRepository/EstimateRepository.java
  src/main/java/com/backend/farmon/repository/EstimateRepository/EstimateRepositoryImpl.java
  src/main/java/com/backend/farmon/service/EstimateService/EstimateQueryServiceImpl.java
Labels: 🐛 fix, ♻️ refactor

#144 ✨[Feat] 전문가 포트폴리오 CRUD api 구현
  build.gradle
  src/main/java/com/backend/farmon/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/backend/farmon/apiPayload/exception/handler/PortfolioHandler.java
  src/main/java/com/backend/farmon/controller/ExpertController.java
  src/main/java/com/backend/farmon/converter/ExpertConverter.java
  src/main/java/com/backend/farmon/domain/Portfolio.java
  src/main/java/com/backend/farmon/domain/PortfolioImg.java
  src/main/java/com/backend/farmon/dto/expert/ExpertListResponse.java
  src/main/java/com/backend/farmon/dto/expert/ExpertProfileRequest.java
  src/main/java/com/backend/farmon/dto/expert/ExpertProfileResponse.java
  src/main/java/com/backend/farmon/dto/expert/PortfolioRequest.java
  src/main/java/com/backend/farmon/dto/expert/PortfolioResponse.java
  src/main/java/com/backend/farmon/repository/PortfolioImgRepository/PortfolioImgRepository.java
  src/main/java/com/backend/farmon/repository/PortfolioRepository/PortfolioRepository.java
  src/main/java/com/backend/farmon/service/AWS/S3Service.java
  src/main/java/com/backend/farmon/service/ExpertService/ExpertCommandService.java
  src/main/java/com/backend/farmon/service/ExpertService/ExpertCommandServiceImpl.java
Labels: ✨ feature

#145 ♻️ refactor Feat /COMMENT 댓글 저장,조회,수정,삭제
  src/main/java/com/backend/farmon/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/backend/farmon/controller/CommentController.java
  src/main/java/com/backend/farmon/controller/PostController.java
  src/main/java/com/backend/farmon/converter/CommentConverter.java
  src/main/java/com/backend/farmon/domain/Comment.java
  src/main/java/com/backend/farmon/dto/Comment/CommentRequestDTO.java
  src/main/java/com/backend/farmon/dto/Comment/CommentResponseDTO.java
  src/main/java/com/backend/farmon/dto/post/PostResponseDTO.java
  src/main/java/com/backend/farmon/repository/CommentRepository/CommentRepository.java
  src/main/java/com/backend/farmon/service/CommentService/CommentService.java
  src/main/java/com/backend/farmon/service/CommentService/CommentServiceImpl.java
  src/main/java/com/backend/farmon/service/PostService/PostQueryServiceImpl.java
Labels: ♻️ refactor

#147 👷[CI] Redis 비밀번호 설정 및 Docker 환경 변수 설정 추가
  .github/workflows/dev-deploy.yml
  Dockerfile
  docker-compose.yml
  redis.conf
  src/main/java/com/backend/farmon/config/RedisConfig.java
  src/main/java/com/backend/farmon/controller/HomeController.java
  src/main/java/com/backend/farmon/controller/TestController.java
  src/main/java/com/backend/farmon/converter/HomeConverter.java
  src/main/java/com/backend/farmon/service/SearchService/SearchQueryService.java
  src/main/java/com/backend/farmon/service/SearchService/SearchQueryServiceImpl.java
Labels: ♻️ refactor, 👷 ci

#152 ✨ Feat: 아이디/비밀번호 찾기 api구현, 전문가 포트폴리오 등록 api 수정
  src/main/java/com/backend/farmon/config/security/SecurityConfig.java
  src/main/java/com/backend/farmon/controller/UserController.java
  src/main/java/com/backend/farmon/repository/UserRepository/UserRepository.java
  src/main/java/com/backend/farmon/service/ExpertService/ExpertCommandServiceImpl.java
Labels: ✨ feature, ♻️ refactor

#153 👷[CI/CD] Docker Compose 파일 복사 및 gradle 빌드 캐시 적용
  .github/workflows/dev-deploy.yml
  docker-compose.yml
Labels: 👷 ci

#155 ♻️[Refactor] 견적 관련 API 코드 보완
  src/main/java/com/backend/farmon/controller/EstimateRestController.java
  src/main/java/com/backend/farmon/service/EstimateService/EstimateQueryServiceImpl.java
Labels: ♻️ refactor

#157 ✨[Feat] 채팅방 접근 권한 및 존재 여부 검증 Aspect & 커스텀 어노테이션 추가
  README.md
  src/main/java/com/backend/farmon/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/backend/farmon/aspects/ChatAuthorizationAspect.java
  src/main/java/com/backend/farmon/controller/ChatRoomController.java
  src/main/java/com/backend/farmon/controller/HomeController.java
  src/main/java/com/backend/farmon/controller/MessageController.java
  src/main/java/com/backend/farmon/controller/UserController.java
  src/main/java/com/backend/farmon/repository/ChatMessageRepository/ChatMessageRepositoryCustom.java
  src/main/java/com/backend/farmon/repository/ChatMessageRepository/ChatMessageRepositoryImpl.java
  src/main/java/com/backend/farmon/repository/ChatRoomReposiotry/ChatRoomRepository.java
  src/main/java/com/backend/farmon/repository/ChatRoomReposiotry/ChatRoomRepositoryCustom.java
  src/main/java/com/backend/farmon/repository/ChatRoomReposiotry/ChatRoomRepositoryImpl.java
  src/main/java/com/backend/farmon/service/ChatMessageService/ChatMessageCommandServiceImpl.java
  src/main/java/com/backend/farmon/service/ChatMessageService/ChatMessageQueryServiceImpl.java
  src/main/java/com/backend/farmon/service/ChatRoomService/ChatRoomCommandService.java
  src/main/java/com/backend/farmon/service/ChatRoomService/ChatRoomCommandServiceImpl.java
  src/main/java/com/backend/farmon/service/ChatRoomService/ChatRoomQueryService.java
  src/main/java/com/backend/farmon/service/ChatRoomService/ChatRoomQueryServiceImpl.java
  src/main/java/com/backend/farmon/service/SearchService/SearchCommandServiceImpl.java
  src/main/java/com/backend/farmon/service/UserService/UserQueryServiceImpl.java
  src/main/java/com/backend/farmon/service/ValidationService/ValidationService.java
  src/main/java/com/backend/farmon/service/ValidationService/ValidationServiceImpl.java
  src/main/java/com/backend/farmon/validaton/annotation/ExistChatRoom.java
  src/main/java/com/backend/farmon/validaton/annotation/ExistUser.java
  src/main/java/com/backend/farmon/validaton/validator/ChatRoomExistValidator.java
  src/main/java/com/backend/farmon/validaton/validator/UserExistValidator.java
  src/main/java/com/backend/farmon/validaton/validator/UserIdEqualsValidator.java
Labels: ✨ feature, ♻️ refactor

#158 🐛 [Fix] 휴대폰 인증문자 전송 오류 수정
  src/main/java/com/backend/farmon/domain/SmsAuth.java
  src/main/java/com/backend/farmon/service/SmsService/SmsServiceImpl.java
Labels: 🐛 fix

#161 ✨[Feat] 채팅에 RabbitMQ 메시지 브로커 적용
  .github/workflows/dev-deploy.yml
  README.md
  build.gradle
  docker-compose.yml
  src/main/java/com/backend/farmon/config/SwaggerConfig.java
  src/main/java/com/backend/farmon/config/chat/FilterChannelInterceptor.java
  src/main/java/com/backend/farmon/config/chat/RabbitMQConfig.java
  src/main/java/com/backend/farmon/config/chat/WebSocketConfig.java
  src/main/java/com/backend/farmon/controller/MessageController.java
  src/main/java/com/backend/farmon/dto/chat/ChatRequest.java
  src/main/java/com/backend/farmon/repository/PostRepository/PostRepositoryCustom.java
  src/main/java/com/backend/farmon/repository/PostRepository/PostRepositoryImpl.java
  src/main/java/com/backend/farmon/service/ChatMessageService/ChatMessageCommandServiceImpl.java
  src/main/java/com/backend/farmon/service/PostService/PostQueryServiceImpl.java
  src/main/java/com/backend/farmon/strategy/postType/AllPostFetchStrategy.java
  src/main/java/com/backend/farmon/strategy/postType/CategoryPostFetchStrategy.java
  src/main/java/com/backend/farmon/strategy/postType/PopularPostFetchStrategy.java
  src/main/java/com/backend/farmon/strategy/postType/PostFetchStrategy.java
Labels: ✨ feature, 👷 ci

#162 👷[CI/CD] .env에 RabbitMQ user, password 추가
  .github/workflows/dev-deploy.yml
  docker-compose.yml
  src/main/java/com/backend/farmon/controller/MessageController.java
Labels: 👷 ci

#164 🐛 [Fix] 휴대폰 인증문자 로직 수정
  src/main/java/com/backend/farmon/controller/SignupController.java
  src/main/java/com/backend/farmon/service/SmsService/SmsService.java
  src/main/java/com/backend/farmon/service/SmsService/SmsServiceImpl.java
Labels: 🐛 fix

#166 CI: 배포 test
  README.md
Labels: 🐛 fix, 👷 ci

#169 🐛[Fix] 홈 화면 게시글 조회 방법 변경 및 응답 DTO에 게시판 타입 추가
  README.md
  src/main/java/com/backend/farmon/converter/HomeConverter.java
  src/main/java/com/backend/farmon/dto/home/HomeResponse.java
  src/main/java/com/backend/farmon/dto/post/PostType.java
  src/main/java/com/backend/farmon/repository/PostRepository/PostRepositoryCustom.java
  src/main/java/com/backend/farmon/repository/PostRepository/PostRepositoryImpl.java
Labels: 🐛 fix

#170 ✨[Feat] 견적 생성 응답 수정
  src/main/java/com/backend/farmon/converter/EstimateConverter.java
  src/main/java/com/backend/farmon/dto/estimate/EstimateResponseDTO.java
Labels: ✨ feature

#171 ✨ Feat/auth paging 페이지마다 인증하는 것과 QnA 답변 삭제
  src/main/java/com/backend/farmon/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/backend/farmon/controller/PostController.java
  src/main/java/com/backend/farmon/converter/AnswerConverter.java
  src/main/java/com/backend/farmon/domain/Answer.java
  src/main/java/com/backend/farmon/domain/Post.java
  src/main/java/com/backend/farmon/repository/AnswerRepository/AnswerImgRepository.java
  src/main/java/com/backend/farmon/repository/AnswerRepository/AnswerRepository.java
  src/main/java/com/backend/farmon/service/BoardService/BoardServiceImpl.java
  src/main/java/com/backend/farmon/service/CommentService/CommentServiceImpl.java
  src/main/java/com/backend/farmon/service/LikeService/LikeServiceImpl.java
  src/main/java/com/backend/farmon/service/PostService/PostQueryServiceImpl.java
Labels: ✨ feature

#174 🐛 fix인증 오류 수정
  src/main/java/com/backend/farmon/service/BoardService/BoardServiceImpl.java
Labels: bug, 🐛 fix

#175 🐛 fix Fix/pagination
  src/main/java/com/backend/farmon/controller/PostController.java
  src/main/java/com/backend/farmon/repository/PostRepository/PostRepositoryImpl.java
  src/main/java/com/backend/farmon/service/PostService/PostQueryServiceImpl.java
Labels: 🐛 fix

#176 🐛 fix 페이징dto null 값처리
  src/main/java/com/backend/farmon/dto/post/PostPagingResponseDTO.java
Labels: 🐛 fix

#177 🐛 fix Fix/pagingdto
  src/main/java/com/backend/farmon/dto/post/PostPagingResponseDTO.java
  src/main/java/com/backend/farmon/repository/PostRepository/PostRepositoryImpl.java
Labels: 🐛 fix

#178 Feat/search and fix
  src/main/java/com/backend/farmon/controller/PostController.java
  src/main/java/com/backend/farmon/repository/PostRepository/PostRepositoryCustom.java
  src/main/java/com/backend/farmon/repository/PostRepository/PostRepositoryImpl.java
  src/main/java/com/backend/farmon/service/PostService/PostQueryService.java
  src/main/java/com/backend/farmon/service/PostService/PostQueryServiceImpl.java
Labels: bug

#179 ♻️ 전문가 조회 관련 api 수정
  src/main/java/com/backend/farmon/converter/ExpertConverter.java
  src/main/java/com/backend/farmon/repository/ExpertReposiotry/ExpertRepositoryImpl.java
Labels: ♻️ refactor

#180 ♻️ 전문가 조회 DTO 수정
  src/main/java/com/backend/farmon/converter/ExpertConverter.java
  src/main/java/com/backend/farmon/dto/expert/ExpertListResponse.java
  src/main/java/com/backend/farmon/dto/expert/ExpertProfileResponse.java
Labels: ♻️ refactor

#181 ♻️ 전문가 경력 저장방식 수정
  src/main/java/com/backend/farmon/controller/ExpertController.java
  src/main/java/com/backend/farmon/converter/ExpertConverter.java
  src/main/java/com/backend/farmon/domain/Expert.java
  src/main/java/com/backend/farmon/service/ExpertService/ExpertCommandService.java
  src/main/java/com/backend/farmon/service/ExpertService/ExpertCommandServiceImpl.java
Labels: ♻️ refactor

#183 👷[CI/CD] 서버 배포 주소에 https 적용
  .github/workflows/dev-deploy.yml
  nginx.conf
  src/main/java/com/backend/farmon/config/SwaggerConfig.java
  src/main/java/com/backend/farmon/config/WebConfig.java
Labels: 👷 ci

#185 🐛[Fix] cors 허용 origins에 프론트 배포 주소 추가
  src/main/java/com/backend/farmon/config/WebConfig.java
Labels: 🐛 fix

#187 🐛[Fix] 채팅방 생성 시에는 AOP 권한 검증 생략 수정
  src/main/java/com/backend/farmon/aspects/ChatAuthorizationAspect.java
Labels: 🐛 fix
